/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyectoFinal.views;

import java.sql.Date;
import java.time.ZoneId;
import javax.swing.JOptionPane;
import proyectoFinal.AccessData.CiudadData;
import proyectoFinal.Entidades.Ciudad;

/**
 *
 * @author julian
 */
public class AdminCiudad extends javax.swing.JInternalFrame {
    CiudadData cd = new CiudadData();
    /**
     * Creates new form AdminCiudad
     */
    public AdminCiudad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfIngreseId = new javax.swing.JTextField();
        jbBuscarCiudad = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jtfIngreseProvincia = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jbCiudadGuardar = new javax.swing.JButton();
        jbCiudadModificar = new javax.swing.JButton();
        jbCiudadNuevo = new javax.swing.JButton();
        jbCiudadSalir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        jDateChooser3 = new com.toedter.calendar.JDateChooser();

        setClosable(true);

        jLabel1.setText("Administrar Ciudad");

        jLabel2.setText("Ingrese:");

        jtfIngreseId.setText("ID");
        jtfIngreseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfIngreseIdActionPerformed(evt);
            }
        });

        jbBuscarCiudad.setText("Buscar");
        jbBuscarCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarCiudadActionPerformed(evt);
            }
        });

        jLabel3.setText("Ciudad:");

        jLabel4.setText("Provincia:");

        jLabel5.setText("Pais:");

        jTextField1.setText("Ingresar");

        jtfIngreseProvincia.setText("Ingresar");

        jTextField2.setText("Ingresar");

        jbCiudadGuardar.setText("Guardar");
        jbCiudadGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCiudadGuardarActionPerformed(evt);
            }
        });

        jbCiudadModificar.setText("Modificar");
        jbCiudadModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCiudadModificarActionPerformed(evt);
            }
        });

        jbCiudadNuevo.setText("Nuevo");
        jbCiudadNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCiudadNuevoActionPerformed(evt);
            }
        });

        jbCiudadSalir.setText("Salir");
        jbCiudadSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCiudadSalirActionPerformed(evt);
            }
        });

        jLabel6.setText("Temporada Alta:");

        jLabel7.setText("Temporada Media:");

        jLabel8.setText("Temporada Baja:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 17, Short.MAX_VALUE)
                .addComponent(jbCiudadGuardar)
                .addGap(18, 18, 18)
                .addComponent(jbCiudadModificar)
                .addGap(18, 18, 18)
                .addComponent(jbCiudadNuevo)
                .addGap(18, 18, 18)
                .addComponent(jbCiudadSalir)
                .addGap(93, 93, 93))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(jtfIngreseId, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(92, 92, 92)
                                .addComponent(jbBuscarCiudad))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField2))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtfIngreseProvincia))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addGap(18, 18, 18)
                                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfIngreseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarCiudad))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfIngreseProvincia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jDateChooser3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbCiudadGuardar)
                    .addComponent(jbCiudadModificar)
                    .addComponent(jbCiudadNuevo)
                    .addComponent(jbCiudadSalir))
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfIngreseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfIngreseIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfIngreseIdActionPerformed

    private void jbCiudadGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCiudadGuardarActionPerformed
        if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jtfIngreseProvincia.getText().isEmpty() || jDateChooser1.getDate()==null || jDateChooser2.getDate()==null || jDateChooser3.getDate()==null){
        JOptionPane.showMessageDialog(this, "Rellene correctamente los campos");
        } else {
            Ciudad ciudad = new Ciudad();
            ciudad.setEstado(true);
            ciudad.setNombre(jTextField1.getText());
            ciudad.setPais(jTextField2.getText());
            ciudad.setProvincia(jtfIngreseProvincia.getText());
            ciudad.setTemAlta(jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            ciudad.setTemMedia(jDateChooser2.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
            ciudad.setTemBaja(jDateChooser3.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
         cd.guardarCiudad(ciudad);
        }
    }//GEN-LAST:event_jbCiudadGuardarActionPerformed

    private void jbBuscarCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarCiudadActionPerformed
        if (jtfIngreseId.getText() != ""){
            if (comprobar(Integer.parseInt(jtfIngreseId.getText()))==true){
         cd.ciudadId(Integer.parseInt(jtfIngreseId.getText()));
         jTextField1.setText(cd.ciudadId(Integer.parseInt(jtfIngreseId.getText())).getNombre());
         jtfIngreseProvincia.setText(cd.ciudadId(Integer.parseInt(jtfIngreseId.getText())).getProvincia());
         jTextField2.setText(cd.ciudadId(Integer.parseInt(jtfIngreseId.getText())).getPais());
         jDateChooser1.setDate(Date.valueOf(cd.ciudadId(Integer.parseInt(jtfIngreseId.getText())).getTemAlta()));
         jDateChooser2.setDate(Date.valueOf(cd.ciudadId(Integer.parseInt(jtfIngreseId.getText())).getTemMedia()));
         jDateChooser3.setDate(Date.valueOf(cd.ciudadId(Integer.parseInt(jtfIngreseId.getText())).getTemBaja()));
            } else {
            JOptionPane.showMessageDialog(this, "Ingrese un id correcto");
            }
        } else {
        JOptionPane.showMessageDialog(this, "Ingrese un id en el campo");
        }
    }//GEN-LAST:event_jbBuscarCiudadActionPerformed

    private void jbCiudadNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCiudadNuevoActionPerformed
       jTextField1.setText("");
       jTextField2.setText("");
       jtfIngreseId.setText("");
       jtfIngreseProvincia.setText("");
       jDateChooser1.setDate(null);
       jDateChooser2.setDate(null);
       jDateChooser3.setDate(null);
    }//GEN-LAST:event_jbCiudadNuevoActionPerformed

    private void jbCiudadSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCiudadSalirActionPerformed
        dispose();
    }//GEN-LAST:event_jbCiudadSalirActionPerformed

    private void jbCiudadModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCiudadModificarActionPerformed
     
        if (jtfIngreseId.getText() != ""){ 
        if(comprobar(Integer.parseInt(jtfIngreseId.getText()))==true){
          if (jTextField1.getText().isEmpty() || jTextField2.getText().isEmpty() || jtfIngreseProvincia.getText().isEmpty() || jDateChooser1.getDate()==null || jDateChooser2.getDate()==null || jDateChooser3.getDate()==null){
              JOptionPane.showMessageDialog(this, "Rellene los campos faltantes o use buscar por ID");
          } else {
           Ciudad ciudad = new Ciudad();    
          ciudad.setEstado(cd.ciudadId(Integer.parseInt(jtfIngreseId.getText())).isEstado());
          ciudad.setNombre(jTextField1.getText());
          ciudad.setPais(jTextField1.getText());
          ciudad.setProvincia(jtfIngreseProvincia.getText());
          ciudad.setTemAlta(jDateChooser1.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
          ciudad.setTemMedia(jDateChooser2.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
          ciudad.setTemBaja(jDateChooser3.getDate().toInstant().atZone(ZoneId.systemDefault()).toLocalDate());
          ciudad.setIdCiudad(Integer.parseInt(jtfIngreseId.getText()));
          cd.modificarCiudad(ciudad);
          }
        } else {
        JOptionPane.showMessageDialog(this, "Ingrese un valor existente");
        }
       } else {
       JOptionPane.showMessageDialog(this, "Ingrese algun valor en el campo ID");
       }
    }//GEN-LAST:event_jbCiudadModificarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateChooser3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton jbBuscarCiudad;
    private javax.swing.JButton jbCiudadGuardar;
    private javax.swing.JButton jbCiudadModificar;
    private javax.swing.JButton jbCiudadNuevo;
    private javax.swing.JButton jbCiudadSalir;
    private javax.swing.JTextField jtfIngreseId;
    private javax.swing.JTextField jtfIngreseProvincia;
    // End of variables declaration//GEN-END:variables

    private boolean comprobar (int id){
    boolean ok = false;
    for (Ciudad c : cd.listarCiudad()){
    if (c.getIdCiudad() == id){
    ok = true;
    }
    }
    return ok;
    }
}
