package proyectoFinal.views;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;

public class Principal extends javax.swing.JFrame {
    
    public static boolean logeado=false;
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/G67TravelPackages.png"));
        Image image = icon.getImage();
        Desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministrar = new javax.swing.JMenu();
        jmCiudad = new javax.swing.JMenuItem();
        jmAlojamiento = new javax.swing.JMenuItem();
        jmPasaje = new javax.swing.JMenuItem();
        jmDesconectarse = new javax.swing.JMenuItem();
        jmPresupuestos = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 627, Short.MAX_VALUE)
        );

        jmAdministrar.setText("Administracion");
        jmAdministrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAdministrarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmAdministrarMousePressed(evt);
            }
        });

        jmCiudad.setText("Adm. ciudades");
        if (logeado){
            jmCiudad.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jmCiudadActionPerformed(evt);
                }
            });
            jmAdministrar.add(jmCiudad);
        }

        jmAlojamiento.setText("Adm. alojamientos");
        if(logeado){
            jmAlojamiento.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jmAlojamientoActionPerformed(evt);
                }
            });
            jmAdministrar.add(jmAlojamiento);
        }

        jmPasaje.setText("Adm. pasajes");
        jmPasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPasajeActionPerformed(evt);
            }
        });
        if(logeado){
            jmAdministrar.add(jmPasaje);
        }

        jmDesconectarse.setText("Desconectarse");
        if(logeado){
            jmDesconectarse.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    jmDesconectarseActionPerformed(evt);
                }
            });
            jmAdministrar.add(jmDesconectarse);
        }

        jMenuBar1.add(jmAdministrar);

        jmPresupuestos.setText("Presupuestos");

        jMenuItem1.setText("jMenuItem1");
        jmPresupuestos.add(jMenuItem1);

        jMenuBar1.add(jmPresupuestos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAdministrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAdministrarMouseClicked
     
       
    }//GEN-LAST:event_jmAdministrarMouseClicked

    private void jmAdministrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAdministrarMousePressed
        if (!logeado) {
            Desktop.removeAll();
            Desktop.repaint();
            Login venlogin = new Login();
            venlogin.setVisible(true);
            Desktop.add(venlogin);
         //   Desktop.moveToFront(venlogin);
            Dimension desktopSize = Desktop.getSize();
            Dimension FrameSize = venlogin.getSize();
            venlogin.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            venlogin.show();
            
        } else {
             jmAdministrar.add(jmCiudad);
             jmAdministrar.add(jmAlojamiento);
             jmAdministrar.add(jmPasaje);
             jmAdministrar.add(jmDesconectarse);
            

        }
    }//GEN-LAST:event_jmAdministrarMousePressed

    private void jmCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCiudadActionPerformed
           
        Desktop.removeAll();
        Desktop.repaint();
        AdminCiudad admCiudad = new AdminCiudad();
        admCiudad.setVisible(true);
        Desktop.add(admCiudad);
        Desktop.moveToFront(admCiudad);
    }//GEN-LAST:event_jmCiudadActionPerformed

    private void jmPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPasajeActionPerformed
        
        Desktop.removeAll();
        Desktop.repaint();
        jifPasaje admPasaje = new jifPasaje();
        admPasaje.setVisible(true);
        Desktop.add(admPasaje);
        Desktop.moveToFront(admPasaje);
        
        
    }//GEN-LAST:event_jmPasajeActionPerformed

    private void jmAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlojamientoActionPerformed
       Desktop.removeAll();
        Desktop.repaint();
        AdminAlojamiento admAlojamineto = new AdminAlojamiento();
        admAlojamineto.setVisible(true);
        Desktop.add(admAlojamineto);
        Desktop.moveToFront(admAlojamineto);
    }//GEN-LAST:event_jmAlojamientoActionPerformed

    private void jmDesconectarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDesconectarseActionPerformed
        
        logeado = false;
    }//GEN-LAST:event_jmDesconectarseActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenu jmAdministrar;
    private javax.swing.JMenuItem jmAlojamiento;
    private javax.swing.JMenuItem jmCiudad;
    private javax.swing.JMenuItem jmDesconectarse;
    private javax.swing.JMenuItem jmPasaje;
    private javax.swing.JMenu jmPresupuestos;
    // End of variables declaration//GEN-END:variables

}
