package proyectoFinal.views;

import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import proyectoFinal.AccessData.Conexion;

public class Principal extends javax.swing.JFrame {
    
    public static boolean logeado=false;
    private Connection con;
    
    public Principal() {
        initComponents();
        this.setLocationRelativeTo(null);
        con = Conexion.getConnection();
        if (con == null) {            
            ImageIcon icono = new ImageIcon("src/Icons/errorDatabase32.png");
            JOptionPane.showMessageDialog(this, "No esta conectado a una base de datos", "Error conexion a base de datos", WIDTH, icono);
            jMenuBar1.setVisible(false);
            
        }else{
            jbReconectar.setVisible(false);
            jbReconectar.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon = new ImageIcon(getClass().getResource("/Icons/G67TravelPackages.png"));
        Image image = icon.getImage();
        Desktop = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jbReconectar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jmAdministrar = new javax.swing.JMenu();
        jmCiudad = new javax.swing.JMenuItem();
        jmAlojamiento = new javax.swing.JMenuItem();
        jmPasaje = new javax.swing.JMenuItem();
        jmDesconectarse = new javax.swing.JMenuItem();
        jmPresupuestos = new javax.swing.JMenu();
        jmArmarPresupuesto = new javax.swing.JMenuItem();
        jmConsultar = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jbReconectar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/Database32 .png"))); // NOI18N
        jbReconectar.setToolTipText("Reconectar base de datos");
        jbReconectar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbReconectarActionPerformed(evt);
            }
        });

        Desktop.setLayer(jbReconectar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout DesktopLayout = new javax.swing.GroupLayout(Desktop);
        Desktop.setLayout(DesktopLayout);
        DesktopLayout.setHorizontalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DesktopLayout.createSequentialGroup()
                .addContainerGap(493, Short.MAX_VALUE)
                .addComponent(jbReconectar)
                .addGap(45, 45, 45))
        );
        DesktopLayout.setVerticalGroup(
            DesktopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DesktopLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jbReconectar, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(545, Short.MAX_VALUE))
        );

        jmAdministrar.setText("Administracion");
        jmAdministrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jmAdministrarMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jmAdministrarMousePressed(evt);
            }
        });

        jmCiudad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/ciuda28.png"))); // NOI18N
        jmCiudad.setText("Adm. ciudades");
        jmCiudad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmCiudadActionPerformed(evt);
            }
        });
        if (logeado){
            jmAdministrar.add(jmCiudad);
        }

        jmAlojamiento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/alojamiento28.png"))); // NOI18N
        jmAlojamiento.setText("Adm. alojamientos");
        jmAlojamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmAlojamientoActionPerformed(evt);
            }
        });
        if(logeado){
            jmAdministrar.add(jmAlojamiento);
        }

        jmPasaje.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/pasaje28.png"))); // NOI18N
        jmPasaje.setText("Adm. pasajes");
        jmPasaje.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmPasajeActionPerformed(evt);
            }
        });
        if(logeado){
            jmAdministrar.add(jmPasaje);
        }

        jmDesconectarse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/adminLogout28.png"))); // NOI18N
        jmDesconectarse.setText("Desconectarse");
        jmDesconectarse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmDesconectarseActionPerformed(evt);
            }
        });
        if(logeado){
            jmAdministrar.add(jmDesconectarse);
        }

        jMenuBar1.add(jmAdministrar);

        jmPresupuestos.setText("Presupuestos");

        jmArmarPresupuesto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/armarPaquete28.png"))); // NOI18N
        jmArmarPresupuesto.setText("Armar presupuesto");
        jmArmarPresupuesto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmArmarPresupuestoActionPerformed(evt);
            }
        });
        jmPresupuestos.add(jmArmarPresupuesto);

        jmConsultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/buscarPaquete28.png"))); // NOI18N
        jmConsultar.setText("Consultar mi presupuesto");
        jmConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmConsultarActionPerformed(evt);
            }
        });
        jmPresupuestos.add(jmConsultar);

        jMenuBar1.add(jmPresupuestos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Desktop, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmAdministrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAdministrarMouseClicked
     
       
    }//GEN-LAST:event_jmAdministrarMouseClicked

    private void jmAdministrarMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jmAdministrarMousePressed
        if (!logeado) {
            Desktop.removeAll();
            Desktop.repaint();
            Login venlogin = new Login();
            venlogin.setVisible(true);
            Desktop.add(venlogin);
            Dimension desktopSize = Desktop.getSize();
            Dimension FrameSize = venlogin.getSize();
            venlogin.setLocation((desktopSize.width - FrameSize.width)/2, (desktopSize.height- FrameSize.height)/2);
            venlogin.show();
            
        } else {
             jmAdministrar.add(jmCiudad);
             jmAdministrar.add(jmAlojamiento);
             jmAdministrar.add(jmPasaje);
             jmAdministrar.add(jmDesconectarse);
            

        }
    }//GEN-LAST:event_jmAdministrarMousePressed

    private void jmCiudadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmCiudadActionPerformed
           
        Desktop.removeAll();
        Desktop.repaint();
        AdminCiudad admCiudad = new AdminCiudad();
        admCiudad.setVisible(true);
        Desktop.add(admCiudad);
        Desktop.moveToFront(admCiudad);
    }//GEN-LAST:event_jmCiudadActionPerformed

    private void jmPasajeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmPasajeActionPerformed
        
        Desktop.removeAll();
        Desktop.repaint();
        AdminPasaje admPasaje = new AdminPasaje();
        admPasaje.setVisible(true);
        Desktop.add(admPasaje);
        Desktop.moveToFront(admPasaje);
        
        
    }//GEN-LAST:event_jmPasajeActionPerformed

    private void jmAlojamientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmAlojamientoActionPerformed
       Desktop.removeAll();
        Desktop.repaint();
        AdminAlojamiento admAlojamineto = new AdminAlojamiento();
        admAlojamineto.setVisible(true);
        Desktop.add(admAlojamineto);
        Desktop.moveToFront(admAlojamineto);
    }//GEN-LAST:event_jmAlojamientoActionPerformed

    private void jmDesconectarseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmDesconectarseActionPerformed
       ImageIcon icono = new ImageIcon("src/Icons/adminAdv32.png");
        int op = JOptionPane.showConfirmDialog(null, "Seguro desea salir",
            "Salir", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE, icono);
        if (op == 0) {
            this.logeado = false;
            jmAdministrar.remove(jmCiudad);
            jmAdministrar.remove(jmAlojamiento);
            jmAdministrar.remove(jmPasaje);
            jmAdministrar.remove(jmDesconectarse);
        }
    }//GEN-LAST:event_jmDesconectarseActionPerformed

    private void jmArmarPresupuestoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmArmarPresupuestoActionPerformed
        Desktop.removeAll();
        Desktop.repaint();

        Presupuesto presupuesto = new Presupuesto ();

        presupuesto.setVisible(true);
        Desktop.add(presupuesto);
        Desktop.moveToFront(presupuesto);
    }//GEN-LAST:event_jmArmarPresupuestoActionPerformed

    private void jmConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmConsultarActionPerformed
       Desktop.removeAll();
        Desktop.repaint();

        PresupuestoV3 consulta = new PresupuestoV3 ();

        consulta.setVisible(true);
        Desktop.add(consulta);
        Desktop.moveToFront(consulta);
    }//GEN-LAST:event_jmConsultarActionPerformed

    private void jbReconectarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbReconectarActionPerformed
        con = Conexion.getConnection();
        if (con == null) {            
            ImageIcon icono = new ImageIcon("src/Icons/errorDatabase32.png");
            JOptionPane.showMessageDialog(this, "No esta conectado a una base de datos",
                    "Error conexion a base de datos", WIDTH, icono);
        } else {
            ImageIcon icono = new ImageIcon("src/Icons/okDatabase32.png");
            JOptionPane.showMessageDialog(this, "Conectado a la base de datos.",
                    "Conexion base de datos", WIDTH, icono);
            jMenuBar1.setVisible(true);
            jbReconectar.setVisible(false);
            jbReconectar.setEnabled(false);
            
        }
    }//GEN-LAST:event_jbReconectarActionPerformed

  
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JDesktopPane Desktop;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JButton jbReconectar;
    private javax.swing.JMenu jmAdministrar;
    private javax.swing.JMenuItem jmAlojamiento;
    private javax.swing.JMenuItem jmArmarPresupuesto;
    private javax.swing.JMenuItem jmCiudad;
    private javax.swing.JMenuItem jmConsultar;
    private javax.swing.JMenuItem jmDesconectarse;
    private javax.swing.JMenuItem jmPasaje;
    private javax.swing.JMenu jmPresupuestos;
    // End of variables declaration//GEN-END:variables

}
